name: davidwolflivingston
favicon: null
layout_spectrum: 0.2081
typography_spectrum: 0.94595
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#7c7c7c'
    - '#b0b0b0'
    - '#3b3b3b'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
